# config.yaml
version_base: 1.1

# List of active models to run (should match keys in the models section)
active_models: ["simpleMoe"]

# List of active datasets to run (should match keys in the data section)
active_datasets: ["m3_monthly"]

models:
  simpleMoe:
    params:
      input_size: 24
      dropout: 0.1
      loss: "SMAPE"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "SMAPE"    # Single string value
      early_stop_patience_steps: 10  # A single number
      batch_size: 32
  nhits:
    params:
      input_size: 24 
      loss: "SMAPE"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "SMAPE"    # Single string value
      early_stop_patience_steps: 10  # A single number
      batch_size: 32
  nbeats:
    params:
      input_size: 24
      loss: "SMAPE"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "SMAPE"    # Single string value
      early_stop_patience_steps: 10  # A single number
      batch_size: 32

data:
  m3_monthly:
    directory: "./data/m3"
    group: "Monthly"
    # List of horizons to test (e.g. forecasting 12, 18, and 24 steps ahead)
    horizons: [18]

forecast:
  default_forecast:
    freq: "M"

plot:
  default_plot:
    figsize: [20, 7]
    save_path: "all_forecasts.png"
    xlabel: "Year"
    ylabel: "y"
    title: "All Forecasts"
    legend_font_size: 15
    grid: true
