# config.yaml
version_base: 1.1

# List of active models to run (should match keys in the models section)
active_models: ["nbeatsMoe", "nbeats"]

# List of active datasets to run (should match keys in the data section)
active_datasets: ["m3_monthly"]

models: 
  simpleMoe:
    params:
      input_size: 24
      dropout: 0.1
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 1000
      batch_size: 32
  nhits:
    params:         
      input_size: 24 
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  nbeats:
    params:
      input_size: 24
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  timeMoeAdapted:
    params:
      input_size: 24
      dropout: 0.1
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  vanillatransformer:
    params:
      input_size: 24
      dropout: 0.1  
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  autoformer:
    params:
      input_size: 24
      dropout: 0.1
      loss: "HuberLoss"         
      valid_loss: "HuberLoss"   
      early_stop_patience_steps: 30
      val_check_steps: 100  
      batch_size: 32
  informerMoe:
    params:
        input_size: 24
        dropout: 0.1
        loss: "HuberLoss"         
        valid_loss: "HuberLoss"   
        early_stop_patience_steps: 10
        val_check_steps: 100
        batch_size: 32
  mlp:
    params:
      input_size: 24
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  mlpMoe:
    params:
      input_size: 24
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
  nbeatsMoe:
    params:
      input_size: 24
      loss: "HuberLoss"         # Single string value (will be eval'd to a loss instance)
      valid_loss: "HuberLoss"    # Single string value
      early_stop_patience_steps: 10  # A single number
      val_check_steps: 100
      batch_size: 32
    

data:
  m3_monthly:
    directory: "C:\\Users\\ricar\\mixture_of_experts_time_series\\data\\m3\\"
    group: "Monthly"
    freq: "M"
    horizons: [12, 18, 24]
  m4_monthly:
    directory: "C:\\Users\\ricar\\mixture_of_experts_time_series\\data\\m4\\"
    group: "Monthly"
    freq: 1
    horizons: [18]


plot:
  default_plot:
    figsize: [20, 7]
    save_path: "all_forecasts.png"
    xlabel: "Year"
    ylabel: "y"
    title: "All Forecasts"
    legend_font_size: 5
    grid: true
