# config.yaml
version_base: 1.1

model:
  simple_moe:
    h: 12
    input_size: 24
    dropout: 0.1
    loss: "SMAPE"
    valid_loss: "SMAPE"
    early_stop_patience_steps: 3
    batch_size: 32

data:
  m3_monthly:
    directory: "./data/m3"
    group: "Monthly"
    horizon: 12

forecast:
  default_forecast:
    freq: "M"

plot:
  default_plot:
    figsize: [20, 7]
    save_path: "all_forecasts.png"
    xlabel: "Year"
    ylabel: "y"
    title: "All Forecasts"
    legend_font_size: 15
    grid: true

